### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by phpslonuk** [phpslonuk/homepage#10]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by MakcumLviv** [comment]
Старший з двох братів Саб-Зіро на ім'я Бі-Хань був введений в першу гру Mortal Kombat , де він бере участь у турнірі «Смертельна битва». Йому було наказано Грандмастером клану Лін Куей вбити господаря турніру Шан Цунг а і забрати його скарб, але він не виконав свою місію, і був убитий привидом Скорпіона, який прагнув помститися за свою смерть. Бі-Хань стає нежиттю по імені Нуб Сайбот.

**Comment by phpslonuk** [comment]
дякую
