### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by phpslonuk** [phpslonuk/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by MakcumLviv** [comment]
Прийоми
Замороження - класичний прийом. Він кидає кулю з льоду, який заморожує супротивника. (UMK3, MKT)
Крижана калюжа - Саб-Зіро заморожує невелику ділянку підлоги. Якщо противник наступить на крижану калюжу, то він буде якийсь час ковзати, і відкритий для ударів. (UMK3, MKT)
Підкат - класичний прийом. Він ковзає по підлозі і збиває супротивника з ніг. (UMK3, MKT)
Крижаний дощ - Саб-Зіро кидає заморозку вертикально вгору. Через секунду вона падає на противника. У цього прийому є три різних комбінації, які дозволяють кидати заморозку перед ворогом, за ворогом, або безпосередньо на противника. (MKT (версія для N64))
Крижаний клон - класичний прийом, Саб-Зіро створює крижану статую. Якщо противник доторкнеться до неї, то він виявиться заморожений. (MKT (версія для N64))
Fatality
Відривання голови - Вириває голову супротивника разом з хребтом. Перед тим, як Саб-Зіро відірве голову ворогові, екран гасне. (UMK3, MKT)
Сталагміт - Підкидає противника вгору аперкотом і поки той перебуває в повітрі, створює величезний крижаний шип, на який падає супротивник. (MKT)

**Comment by phpslonuk** [comment]
дякую
